# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('opening_date', models.DateField()),
                ('opening_balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credit', models.FloatField(blank=True, default=0, null=True)),
                ('debit', models.FloatField(blank=True, default=0, null=True)),
                ('libelle', models.TextField(blank=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mescomptes.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('symbol', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='compte',
            name='devise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mescomptes.Devise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compte',
            name='opening_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compte',
            name='opening_balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='compte',
            name='opening_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('mensualiser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='mescomptes.Categorie'),
        ),
    ]
