# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('opening_date', models.DateField()),
                ('opening_balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('credit', models.BigIntegerField(default=0)),
                ('debit', models.BigIntegerField(default=0)),
                ('libelle', models.TextField(blank=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mescomptes.Compte')),
            ],
        ),
    ]
