# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0001_squashed_0002_auto_20180829_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='compte',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
