# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0002_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='devise',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mescomptes.Devise'),
            preserve_default=False,
        ),
    ]
