# Generated by Django 5.1.4 on 2024-12-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0003_alter_categorie_id_alter_compte_id_alter_devise_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='regex',
            field=models.TextField(blank=True),
        ),
    ]
