# Generated by Django 5.1.4 on 2024-12-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0004_categorie_regex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='regex',
        ),
        migrations.AddField(
            model_name='categorie',
            name='regexs',
            field=models.ManyToManyField(to='mescomptes.regex'),
        ),
    ]
