# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0008_auto_20180825_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='mensualiser',
        ),
        migrations.AddField(
            model_name='categorie',
            name='mensualiser',
            field=models.BooleanField(default=False),
        ),
    ]
