# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-25 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mescomptes', '0010_auto_20180826_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='mescomptes.Categorie'),
        ),
    ]
